version: "3"


services:
  vnc:

    image: digitalorganic/desktop-python-firefox:1.0
    restart: always
    ports:
      - "5901:5901"
    networks:
      - internal
    labels:
      - traefik.enable=false


networks:
  internal:
